name: CI

on:
    - push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: cachix/install-nix-action@v20
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
            - run: nix develop . -c gradle check
